### ISSUE TITLE
raise KeyError(key)     KeyError: 'Configuration'

### ISSUE THREAD

**Issue by Ricardoliyan** [PaddlePaddle/MetaGym#65]
运行liftsim中test文件里的qa_test.py时
Traceback (most recent call last):
  File "E:/xunleidownload/MetaGym-master/MetaGym-master/metagym/liftsim/tests/qa_test.py", line 332, in <module>
    run_qa_test('metagym/liftsim/tests/conf/config1.ini', 4000, 'rule_benchmark', set_seed) # 1 elevator
  File "E:/xunleidownload/MetaGym-master/MetaGym-master/metagym/liftsim/tests/qa_test.py", line 270, in run_qa_test
    mansion_env = LiftSim(configfile)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\metagym\liftsim\environment\env.py", line 47, in __init__
    time_step = float(config['Configuration']['RunningTimeStep'])
  File "C:\Users\Administrator\anaconda3\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Configuration'

进程已结束，退出代码为 1
报错怎么解决呢

**Comment by Ricardoliyan** [comment]
已解决，文件路径用绝对路径就可以了
